version: "3"
services:
  rabbitmq:
    image: rabbitmq:latest
    restart: always
    hostname: rabbitmqhost
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --reload --timeout 10
    env_file:
      - env/order_mongodb.env
    environment:
      - GATEWAY_URL=http://gateway:80
    depends_on:
      rabbitmq:
        condition: service_healthy
  ## Order Router
  order_router01:
    image: mongo:6.0.1
    container_name: order_router-01
    command: mongos --port 27017 --configdb order_rs-config-server/order_configserver01:27017,order_configserver02:27017,order_configserver03:27017 --bind_ip_all
    ports:
      - 28017:27017
    restart: always
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_router01_db:/data/db
      - mongodb_cluster_order_router01_config:/data/configdb

  order_router02:
    image: mongo:6.0.1
    container_name: order_router-02
    command: mongos --port 27017 --configdb order_rs-config-server/order_configserver01:27017,order_configserver02:27017,order_configserver03:27017 --bind_ip_all
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_router02_db:/data/db
      - mongodb_cluster_order_router02_config:/data/configdb
    ports:
      - 28118:27017
    restart: always
    links:
      - order_router01

  ## Config Servers
  order_configserver01:
    image: mongo:6.0.1
    container_name: mongo-order-config-01
    command: mongod --port 27017 --configsvr --replSet order_rs-config-server
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_configserver01_db:/data/db
      - mongodb_cluster_order_configserver01_config:/data/configdb
    ports:
      - 28119:27017
    restart: always
    links:
      - order_shard01-a
      - order_shard02-a
      - order_shard03-a

  order_configserver02:
    image: mongo:6.0.1
    container_name: mongo-order-config-02
    command: mongod --port 27017 --configsvr  --replSet order_rs-config-server
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_configserver02_db:/data/db
      - mongodb_cluster_order_configserver02_config:/data/configdb
    ports:
      - 28120:27017
    restart: always
    links:
      - order_configserver01

  order_configserver03:
    image: mongo:6.0.1
    container_name: mongo-order-config-03
    command: mongod --port 27017 --configsvr  --replSet order_rs-config-server
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_configserver03_db:/data/db
      - mongodb_cluster_order_configserver03_config:/data/configdb
    ports:
      - 28121:27017
    restart: always
    links:
      - order_configserver02

  ## order_shards
  ## order_shards 01

  order_shard01-a:
    image: mongo:6.0.1
    container_name: order_shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-01
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard01_a_db:/data/db
      - mongodb_cluster_order_shard01_a_config:/data/configdb
    ports:
      - 28122:27017
    restart: always
    links:
      - order_shard01-b
      - order_shard01-c

  order_shard01-b:
    image: mongo:6.0.1
    container_name: order_shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-01
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard01_b_db:/data/db
      - mongodb_cluster_order_shard01_b_config:/data/configdb
    ports:
      - 28123:27017
    restart: always

  order_shard01-c:
    image: mongo:6.0.1
    container_name: order_shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-01
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard01_c_db:/data/db
      - mongodb_cluster_order_shard01_c_config:/data/configdb
    ports:
      - 28124:27017
    restart: always

  ## order_shards 02
  order_shard02-a:
    image: mongo:6.0.1
    container_name: order_shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-02
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard02_a_db:/data/db
      - mongodb_cluster_order_shard02_a_config:/data/configdb
    ports:
      - 28125:27017
    restart: always
    links:
      - order_shard02-b
      - order_shard02-c

  order_shard02-b:
    image: mongo:6.0.1
    container_name: order_shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-02
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard02_b_db:/data/db
      - mongodb_cluster_order_shard02_b_config:/data/configdb
    ports:
      - 28126:27017
    restart: always

  order_shard02-c:
    image: mongo:6.0.1
    container_name: order_shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-02
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard02_c_db:/data/db
      - mongodb_cluster_order_shard02_c_config:/data/configdb
    ports:
      - 28127:27017
    restart: always

  ## order_shards 03
  order_shard03-a:
    image: mongo:6.0.1
    container_name: order_shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-03
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard03_a_db:/data/db
      - mongodb_cluster_order_shard03_a_config:/data/configdb
    ports:
      - 28128:27017
    restart: always
    links:
      - order_shard03-b
      - order_shard03-c

  order_shard03-b:
    image: mongo:6.0.1
    container_name: order_shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-03
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard03_b_db:/data/db
      - mongodb_cluster_order_shard03_b_config:/data/configdb
    ports:
      - 28129:27017
    restart: always

  order_shard03-c:
    image: mongo:6.0.1
    container_name: order_shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet rs-order_shard-03
    volumes:
      - ./order/scripts:/order/scripts
      - mongodb_cluster_order_shard03_c_db:/data/db
      - mongodb_cluster_order_shard03_c_config:/data/configdb
    ports:
      - 28130:27017
    restart: always

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    env_file:
      - env/stock_postgresql.env
    environment:
      - GATEWAY_URL=http://gateway:80
    restart: always
    depends_on:
      stock-db:
        condition: service_healthy

  stock-db:
    image: postgres:latest
    restart: always
    env_file:
      - env/stock_postgresql.env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./stock/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - ./stock/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./stock/create_user.sql:/docker-entrypoint-initdb.d/create_user.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-service:
    build: ./payment
    image: payment:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    env_file:
      - env/payment_mongodb.env
    environment:
      - GATEWAY_URL=http://gateway:80

  payment-consumer:
    build: ./rabbitmq/consumers/payment
    image: payment-consumer:latest
    command: python consumer.py
    env_file:
      - env/payment_mongodb.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./rabbitmq/consumers/payment:/HOME/FLASK-APP

  stock-consumer:
    build: ./rabbitmq/consumers/stock
    image: stock-consumer:latest
    command: python consumer.py
    env_file:
      - env/stock_postgresql.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./rabbitmq/consumers/stock:/HOME/FLASK-APP

  ## Payment routers
  payment_router01:
    image: mongo:6.0.1
    container_name: payment_router-01
    command: mongos --port 27017 --configdb payment_rs-config-server/payment_configsvr01:27017,payment_configsvr02:27017,payment_configsvr03:27017 --bind_ip_all
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_router01_db:/data/db
      - payment_mongodb_cluster_router01_config:/data/configdb

  payment_router02:
    image: mongo:6.0.1
    container_name: payment_router-02
    command: mongos --port 27017 --configdb payment_rs-config-server/payment_configsvr01:27017,payment_configsvr02:27017,payment_configsvr03:27017 --bind_ip_all
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_router02_db:/data/db
      - payment_mongodb_cluster_router02_config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    links:
      - payment_router01

  ## Payment config Servers
  payment_configsvr01:
    image: mongo:6.0.1
    container_name: payment_mongo-config-01
    command: mongod --port 27017 --configsvr --replSet  payment_rs-config-server
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_configsvr01_db:/data/db
      - payment_mongodb_cluster_configsvr01_config:/data/configdb
    ports:
      - 27119:27017
    restart: always
    links:
      - payment_shard01-a
      - payment_shard02-a
      - payment_shard03-a

  payment_configsvr02:
    image: mongo:6.0.1
    container_name: payment_mongo-config-02
    command: mongod --port 27017 --configsvr --replSet payment_rs-config-server
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_configsvr02_db:/data/db
      - payment_mongodb_cluster_configsvr02_config:/data/configdb
    ports:
      - 27120:27017
    restart: always
    links:
      - payment_configsvr01

  payment_configsvr03:
    image: mongo:6.0.1
    container_name: payment_mongo-config-03
    command: mongod --port 27017 --configsvr --replSet payment_rs-config-server
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_configsvr03_db:/data/db
      - payment_mongodb_cluster_configsvr03_config:/data/configdb
    ports:
      - 27121:27017
    restart: always
    links:
      - payment_configsvr02

  ## Payment shards

  ## Payment shard 01

  payment_shard01-a:
    image: mongo:6.0.1
    container_name: payment_shard-01-node-a
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-01
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard01_a_db:/data/db
      - payment_mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27122:27017
    restart: always
    links:
      - payment_shard01-b
      - payment_shard01-c

  payment_shard01-b:
    image: mongo:6.0.1
    container_name: payment_shard-01-node-b
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-01
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard01_b_db:/data/db
      - payment_mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27123:27017
    restart: always

  payment_shard01-c:
    image: mongo:6.0.1
    container_name: payment_shard-01-node-c
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-01
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard01_c_db:/data/db
      - payment_mongodb_cluster_shard01_c_config:/data/configdb
    ports:
      - 27124:27017
    restart: always

  ## Payment shard 02
  payment_shard02-a:
    image: mongo:6.0.1
    container_name: payment_shard-02-node-a
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-02
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard02_a_db:/data/db
      - payment_mongodb_cluster_shard02_a_config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    links:
      - payment_shard02-b
      - payment_shard02-c

  payment_shard02-b:
    image: mongo:6.0.1
    container_name: payment_shard-02-node-b
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-02
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard02_b_db:/data/db
      - payment_mongodb_cluster_shard02_b_config:/data/configdb
    ports:
      - 27126:27017
    restart: always

  payment_shard02-c:
    image: mongo:6.0.1
    container_name: payment_shard-02-node-c
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-02
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard02_c_db:/data/db
      - payment_mongodb_cluster_shard02_c_config:/data/configdb
    ports:
      - 27127:27017
    restart: always

  ## Payment shard 03
  payment_shard03-a:
    image: mongo:6.0.1
    container_name: payment_shard-03-node-a
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-03
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard03_a_db:/data/db
      - payment_mongodb_cluster_shard03_a_config:/data/configdb
    ports:
      - 27128:27017
    restart: always
    links:
      - payment_shard03-b
      - payment_shard03-c

  payment_shard03-b:
    image: mongo:6.0.1
    container_name: payment_shard-03-node-b
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-03
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard03_b_db:/data/db
      - payment_mongodb_cluster_shard03_b_config:/data/configdb
    ports:
      - 27129:27017
    restart: always

  payment_shard03-c:
    image: mongo:6.0.1
    container_name: payment_shard-03-node-c
    command: mongod --port 27017 --shardsvr --replSet payment_rs-shard-03
    volumes:
      - ./payment/scripts:/payment/scripts
      - payment_mongodb_cluster_shard03_c_db:/data/db
      - payment_mongodb_cluster_shard03_c_config:/data/configdb
    ports:
      - 27130:27017
    restart: always

volumes:
  order_mongodb_data:
    driver: local
  payment_mongodb_data:
    driver: local
  stock_postgres_data:
    driver: local

  mongodb_cluster_order_router01_db:
  mongodb_cluster_order_router01_config:

  mongodb_cluster_order_router02_db:
  mongodb_cluster_order_router02_config:

  mongodb_cluster_order_configserver01_db:
  mongodb_cluster_order_configserver01_config:

  mongodb_cluster_order_configserver02_db:
  mongodb_cluster_order_configserver02_config:

  mongodb_cluster_order_configserver03_db:
  mongodb_cluster_order_configserver03_config:

  mongodb_cluster_order_shard01_a_db:
  mongodb_cluster_order_shard01_a_config:

  mongodb_cluster_order_shard01_b_db:
  mongodb_cluster_order_shard01_b_config:

  mongodb_cluster_order_shard01_c_db:
  mongodb_cluster_order_shard01_c_config:

  mongodb_cluster_order_shard02_a_db:
  mongodb_cluster_order_shard02_a_config:

  mongodb_cluster_order_shard02_b_db:
  mongodb_cluster_order_shard02_b_config:

  mongodb_cluster_order_shard02_c_db:
  mongodb_cluster_order_shard02_c_config:

  mongodb_cluster_order_shard03_a_db:
  mongodb_cluster_order_shard03_a_config:

  mongodb_cluster_order_shard03_b_db:
  mongodb_cluster_order_shard03_b_config:

  mongodb_cluster_order_shard03_c_db:
  mongodb_cluster_order_shard03_c_config:
  payment_mongodb_cluster_router01_db:
  payment_mongodb_cluster_router01_config:

  payment_mongodb_cluster_router02_db:
  payment_mongodb_cluster_router02_config:

  payment_mongodb_cluster_configsvr01_db:
  payment_mongodb_cluster_configsvr01_config:

  payment_mongodb_cluster_configsvr02_db:
  payment_mongodb_cluster_configsvr02_config:

  payment_mongodb_cluster_configsvr03_db:
  payment_mongodb_cluster_configsvr03_config:

  payment_mongodb_cluster_shard01_a_db:
  payment_mongodb_cluster_shard01_a_config:

  payment_mongodb_cluster_shard01_b_db:
  payment_mongodb_cluster_shard01_b_config:

  payment_mongodb_cluster_shard01_c_db:
  payment_mongodb_cluster_shard01_c_config:

  payment_mongodb_cluster_shard02_a_db:
  payment_mongodb_cluster_shard02_a_config:

  payment_mongodb_cluster_shard02_b_db:
  payment_mongodb_cluster_shard02_b_config:

  payment_mongodb_cluster_shard02_c_db:
  payment_mongodb_cluster_shard02_c_config:

  payment_mongodb_cluster_shard03_a_db:
  payment_mongodb_cluster_shard03_a_config:

  payment_mongodb_cluster_shard03_b_db:
  payment_mongodb_cluster_shard03_b_config:

  payment_mongodb_cluster_shard03_c_db:
  payment_mongodb_cluster_shard03_c_config:
