apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o .\test2\
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: order-shard03-c
  name: order-shard03-c
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-shard03-c
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o .\test2\
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/wdm-default: "true"
        io.kompose.service: order-shard03-c
    spec:
      containers:
        - args:
            - mongod
            - --port
            - "27017"
            - --shardsvr
            - --replSet
            - rs-order_shard-03
          image: mongo:6.0.1
          name: order-shard-03-node-c
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-cluster-order-shard03-c-db
            - mountPath: /data/configdb
              name: mongodb-cluster-order-shard03-c-config
      restartPolicy: Always
      volumes:
        - name: mongodb-cluster-order-shard03-c-db
          persistentVolumeClaim:
            claimName: mongodb-cluster-order-shard03-c-db
        - name: mongodb-cluster-order-shard03-c-config
          persistentVolumeClaim:
            claimName: mongodb-cluster-order-shard03-c-config
status: {}
