apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o .\test2\
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: order-router02
  name: order-router02
spec:
  ports:
    - name: "28118"
      port: 28118
      targetPort: 27017
  selector:
    io.kompose.service: order-router02
status:
  loadBalancer: {}
