apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    component: payment
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment
  template:
    metadata:
      labels:
        component: payment
    spec:
      containers:
        - name: payment
          image: ghcr.io/leonkempen/wdm-payment:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "100Mi"
              cpu: "1"
            requests:
              memory: "100Mi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "app:app"]
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-master
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "0"
            - name: MONGODB_DATABASE
              value: "payment_mongodb"
            - name: MONGODB_PASSWORD
              value: "password"
            - name: MONGODB_HOSTNAME
              value: "payment-router01"
            - name: MONGODB_HOSTNAME_2
              value: "payment-router02"
            - name: "GATEWAY_URL"
              value: "http://gateway:80"