apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stock-db
  labels:
    app: stock-db
    tier: database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stock-db
  template:
    metadata:
      labels:
        app: stock-db
        tier: database
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          imagePullPolicy: "Always"
          env:
            - name: POSTGRES_DB
              value: stock
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_HOST
              value: stock-db
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: stock-db-claim0
              mountPath: /var/lib/postgresql/data

            - mountPath: /docker-entrypoint-initdb.d
              name: postgresql-initdb
      volumes:
        - name: stock-db-claim0
          persistentVolumeClaim:
            claimName: stock-db-claim0

        - name: postgresql-initdb
          configMap:
            name: stock-initdb-config