apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o ./test2/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    io.kompose.service: gateway
status:
  loadBalancer: {}
