apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o .\test2\
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: order-configserver03
  name: order-configserver03
spec:
  ports:
    - name: "28121"
      port: 28121
      targetPort: 27017
  selector:
    io.kompose.service: order-configserver03
status:
  loadBalancer: {}
