apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o ./test2/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: order-shard01-a
  name: order-shard01-a
spec:
  ports:
    - name: "28122"
      port: 28122
      targetPort: 27017
  selector:
    io.kompose.service: order-shard01-a
status:
  loadBalancer: {}
