apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o .\test2\
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: order-router02
  name: order-router02
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-router02
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o .\test2\
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/wdm-default: "true"
        io.kompose.service: order-router02
    spec:
      containers:
        - args:
            - mongos
            - --port
            - "27017"
            - --configdb
            - order_rs-config-server/order-configserver01:28119,order-configserver02:28120,order-configserver03:28121
          image: mongo:6.0.1
          name: order-router-02
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-cluster-order-router02-db
            - mountPath: /data/configdb
              name: mongodb-cluster-order-router02-config
      restartPolicy: Always
      volumes:
        - name: mongodb-cluster-order-router02-db
          persistentVolumeClaim:
            claimName: mongodb-cluster-order-router02-db
        - name: mongodb-cluster-order-router02-config
          persistentVolumeClaim:
            claimName: mongodb-cluster-order-router02-config
status: {}
