apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o .\test2\
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-shard02-b
  name: payment-shard02-b
spec:
  ports:
    - name: "27126"
      port: 27126
      targetPort: 27017
  selector:
    io.kompose.service: payment-shard02-b
status:
  loadBalancer: {}
