apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-initdb-config
data:
  init.sql: |
    CREATE TABLE stock (
        id SERIAL PRIMARY KEY,
        price INT NOT NULL,
        stock INT NOT NULL
    );
    