apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o ./test2/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-db
  name: stock-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: stock-db
status:
  loadBalancer: {}
