apiVersion: v1
kind: Service
metadata:
  name: stock-db
  labels:
    app: stock-db
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: stock-db
    tier: database