apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o ./test2/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-service
  name: stock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stock-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o ./test2/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/wdm-default: "true"
        io.kompose.service: stock-service
    spec:
      containers:
        - args:
            - gunicorn
            - -b
            - 0.0.0.0:5000
            - app:app
            - -w
            - "1"
            - --timeout
            - "10"
          env:
            - name: GATEWAY_URL
              value: http://gateway:80
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-stock-postgresql-env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env-stock-postgresql-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-stock-postgresql-env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env-stock-postgresql-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-stock-postgresql-env
          image: ghcr.io/leonkempen/wdm-stock:latest
          name: stock-service
          resources: {}
      restartPolicy: Always
status: {}
