apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o ./test2/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-service
  name: stock-service
spec:
  ports:
    - name: "50000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: stock-service
status:
  loadBalancer: {}
