apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o ./test2/
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-consumer
  name: stock-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stock-consumer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Projects\WDM\kompose-windows-amd64.exe convert -o ./test2/
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/wdm-default: "true"
        io.kompose.service: stock-consumer
    spec:
      containers:
        - args:
            - python
            - consumer.py
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-stock-postgresql-env
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: env-stock-postgresql-env
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-stock-postgresql-env
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env-stock-postgresql-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-stock-postgresql-env
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-stock-postgresql-env
            - name: BASIC_REDIS_URL
              value: redis://my-release-redis-cluster-
          image: stock-consumer-newest
          imagePullPolicy: Never
          name: stock-consumer
          resources: {}
          volumeMounts:
            - mountPath: /HOME/FLASK-APP
              name: stock-consumer-claim0
      restartPolicy: Always
      volumes:
        - name: stock-consumer-claim0
          persistentVolumeClaim:
            claimName: stock-consumer-claim0
status: {}
