name: Build and Test

on:
  push:
    branches: '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run docker and tests
      run: | 
        docker compose up -d
        sleep 5
        python test/test_microservices.py
